### PR TITLE
Update lazy_load.lua

### PR DESCRIPTION
**Pull request by tomasky**
just check dir ,not check every file

### CODE REVIEW

**Comment by siduck** [comment]
@tomasky what if i open a file whose cwd isnt a git dir?

**Comment by tomasky** [comment]
if I open a new file a ,then open a git tracked file b in new buffer,the b file not display gitsigns

**Comment by tomasky** [comment]
But  if I open a newfile `a` ,then open a git tracked file `b` in new buffer ,then open another git tracked `c` ,then c file will show gitsign

**Comment by siduck** [comment]
this is weird, goes out of my head xD

**Comment by tomasky** [comment]
this is because  `vim.fn.expand "%"` ,You can test  the result,

**Comment by siduck** [comment]
> this is because `vim.fn.expand "%"` ,You can test the result,

for example ~/.config/nvim is a git dir

and then im on home folder currently 

Then i run nvim ~/.config/nvim/init.lua

The cwd is /home/sid now which isnt a git dir, so how will the function load gitsigns on gitracked file if we arent currently on git repo

**Comment by tomasky** [comment]
> 

No , I'm always in the current directory，and all files are in the current directory which is a git project dir

**Comment by siduck** [comment]
> > 
> 
> No , I'm always in the current directory，and all files are in the current directory which is a git project dir

oh thats a special edgecase then I think

**Comment by tomasky** [comment]
Sorry ,i cant record video ,but you cant print the result :
```lua
if lines ~= { "" } then
print(  vim.fn.expand "%")
            
vim.loop.spawn("git", {
               args = {
                  "ls-files",
                  "--error-unmatch",
                  vim.fn.expand "%",
               },
            }, onexit)
         end
```

**Comment by siduck** [comment]
image

**Comment by tomasky** [comment]
Just in a git dir ,and open nvim-tree as usual , new a file , then open other files.

**Pull request merged**
