### PR TITLE
Aquarium Theme

### PR DESCRIPTION
**Pull request by FrenzyExists**
Made an Aquarium theme for NvChad, hope you guys like it!

### CODE REVIEW

**Comment by FrenzyExists** [comment]
Ah I see, oki oki. I'll make a PR there. Thanks! :+1:

**Comment by siduck76** [comment]
@FrenzyExists thanks for this! btw check https://github.com/chriskempson/base16/blob/master/styling.md . I cant merge this yet xD. our theme switcher will check for both the themes , in nvchad lua/colors/themes and the nvimbase16 plugin. Name the theme as aquarium-base16.lua https://github.com/NvChad/nvim-base16.lua/tree/master/lua/themes

**Comment by FrenzyExists** [comment]
Thanks for the heads up! I made a PR at the base-16 repo, aaaand I didn't saw your message til now and named it aquarium.lua. I'll fix the naming and PR it :+1:

**Comment by siduck76** [comment]
> Thanks for the heads up! I made a PR at the base-16 repo, aaaand I didn't saw your message til now and named it aquarium.lua. I'll fix the naming and PR it

yea , check colors/highlights.lua to know where are the colors used

**Pull request merged**
