### PR TITLE
chore(nvim-tree): Move some settings to setup

### PR DESCRIPTION
**Pull request by ashincoder**
In this PR some settings like width, side have been moved to the setup. And the keymappings are removed cause they are by default. So why bother adding.

### CODE REVIEW

**Comment by macarthy** [comment]
I have a branch submitted on the same issue.  But you are right about the settings if the are exactly the same 

Are you missing allow_resize = true,  or is that true by default ?

**Comment by macarthy** [comment]
Also I was getting an error with Just doing more testing and seem to have a issue with
the below key binding, is it working on your commit ? 
 { key = "g?", cb = tree_cb "toggle_help" }

**Review by siduck76 — COMMENTED** [review]
@ashincoder  https://github.com/NvChad/NvChad/pull/497

**Comment by ashincoder** [comment]
> I have a branch submitted on the same issue. But you are right about the settings if the are exactly the same
> 
> Are you missing allow_resize = true, or is that true by default ?

Oh yeah just saw that. I just saw the change in nvim-tree and just made it up.

**Pull request closed without merging**
