### PR TITLE
fix: directories not detected as git repos

### PR DESCRIPTION
**Pull request by lucario387**
This fixes NvChad not capable of detecting files from git repo as false if such file's $PWD does not have a `.git` directory
@Akianonymus can you have a look? Tyvm

### CODE REVIEW

**Comment by siduck** [comment]
@lucario387 can you show the behaviour with / without this PR?

**Comment by lucario387** [comment]
Before: For example, if you have a file structure of
├── .git
│  ├── branches
│  ├── COMMIT_EDITMSG
│  ├── config
│  ├── description
│  ├── FETCH_HEAD
│  ├── HEAD
│  ├── hooks
│  ├── index
│  ├── info
│  ├── logs
│  ├── objects
│  ├── ORIG_HEAD
│  ├── packed-refs
│  └── refs
├── .github
│  ├── CONTRIBUTING.md
│  ├── FUNDING.yml
│  ├── ISSUE_TEMPLATE
│  ├── PULL_REQUEST_TEMPLATE
│  ├── README.md
│  └── workflows
├── .gitignore
├── .stylua.toml
├── examples
│  ├── chadrc.lua
│  └── init.lua
├── init.lua
├── LICENSE
├── lua
│  ├── core
│  └── plugins
└── plugin
[Screencast from 2022年08月15日 19時50分57秒.webm](https://user-images.githubusercontent.com/29790821/184623032-9075b38d-4825-4efe-9316-319baf7280f9.webm)

**Comment by lucario387** [comment]
@siduck Let's consider we have a directory structure of 
```
nvim
├── .git
├── .gitignore
├── .stylua.toml
├── examples
│  ├── chadrc.lua
│  └── init.lua
├── init.lua
├── LICENSE
├── lua
└── plugin
```   
If I start from, or `:cd` to `nvim`, then nothing happens, as `vim.fn.isdirectory` will detect up to the current cd, which is `nvim`, as it contains a `.git` directory.   
But if instead, I `:cd` into `nvim/examples`, and then open neovim, it will not detect current directory as inside a git repo, even though it clearly is

With the fix, this should not happen, as it will check recursively up to `/` to find whether it is under a git repo or not

**Comment by lucario387** [comment]
[Screencast from 2022年08月15日 19時50分57秒.webm](https://user-images.githubusercontent.com/29790821/184623764-a8ee0d35-0bb0-4b93-a9f4-e6f9170a9e8f.webm)
Video proof @siduck

**Comment by lucario387** [comment]
@siduck preview video   

When my current directory is ~/.config/nvim (NvChad's repo), then it detects it's a git repo, but when I change the curdir to ~/.config/nvim/lua, it no longer detects it as one.   
With this PR, even when I'm inside ~/.config/nvim/lua, it will still be able to detect it is a git repo

https://user-images.githubusercontent.com/29790821/184638130-8d6f3550-f96a-4a74-992a-cb3c33f29a1f.mp4

**Comment by Akianonymus** [comment]
@siduck In future prs, if multiple commits are a part of single stuff, then squash and merge and ask the pull requestor to make a single commit ( or split sanely ) and then merge. 

Otherwise the git history is just getting useless commits

**Pull request merged**
