### PR TITLE
chore: migrate to neovim v0.7

### PR DESCRIPTION
**Pull request by ahhshm**
- the `filetype.nvim` plugin is removed since `filetype.lua` is build into neovim v0.7
- autocommands are written with Lua
- `utils.map` is rewritten to use `vim.keymap` instead of `nvim_set_keymap`

TODO:
- [ ] rewrite highlight utils with `nvim_set_hl`

### CODE REVIEW

**Comment by ahhshm** [comment]
> its not stable yet. wait for it to launch

Yes I know, that's why I mentioned  "Nevim v0.7 will be realized on Sep 15, So don't merge it until then". I guess APIs are stable enough for this PR

**Comment by bryant-the-coder** [comment]
anything i can help with this?

**Comment by ahhshm** [comment]
Thanks. maybe you can test this out and see if there is a particular problem.

What do you think about [the global statusline](https://www.youtube.com/watch?v=jH5PNvJIa6o)? do you think it is worth working on it?

**Comment by bryant-the-coder** [comment]
Different people will have different opinion. In my humble opinion, you can add the disable option for users. I personally like global statusline

**Comment by bryant-the-coder** [comment]
You do know that the statusline are taking up some space without / with global status.

**Comment by ahhshm** [comment]
That space is taken whether we use global statusline or not. Even in the current setup, the unused spaces are visible enough to annoy people with small screens. Changing highlights might make it more tolerable.

**Comment by zbirenbaum** [comment]
It will need to be updated, but I've had the rewrite for nvim-base16 and our highlights in terms of vim.highlight done for a while. I have daily driven it for a few months now. When I have a change I'll update everything, fix anything that's missing, and add it to this.

https://github.com/zbirenbaum/nvim-base16.lua
https://github.com/zbirenbaum/NvCustom/blob/main/colors/highlights.lua
https://github.com/zbirenbaum/NvCustom/blob/main/colors/init.lua

**Comment by bryant-the-coder** [comment]
@zbirenbaum i might use your code and modify mine. you can check mind btw

**Comment by zbirenbaum** [comment]
> @zbirenbaum i might use your code and modify mine. you can check mind btw

It wasn’t a small rewrite so I’d prefer to commit that myself unless you feel very strongly about it.

**Comment by bryant-the-coder** [comment]
I have a nightly branch. check that branch. feel free to make a PR.

**Comment by zbirenbaum** [comment]
> I have a nightly branch. check that branch. feel free to make a PR.

If you are referring to a personal config or something I don't think I'll be able to any time soon. 

I'm pretty busy right now and have two large repositories to maintain on top of my own plugins 😕

**Comment by bryant-the-coder** [comment]
@ahhshm i will help with the overrides

**Comment by ahhshm** [comment]
@bryant-the-coder What overrides?
I appreciate your willingness to help but I don't think there is much work to do here. @zbirenbaum and I will do the highlight things and that's it.

**Comment by ahhshm** [comment]
@zbirenbaum Have you made any progress on this? I can do it myself if you don't have time.

**Comment by zbirenbaum** [comment]
> @zbirenbaum Have you made any progress on this? I can do it myself if you are busy.

I finished updating the base-16 for earlier today, but rebase did some weird stuff so reset and pasted in the correct files just now, now my fork has no conflicts.. I told siduck earlier but he didn't think its a priority to take care of rn.

If you just want the HL stuff, idk how much of it is default, but it should be pretty easy to check if it is and change to value on anything that isn't.
https://github.com/zbirenbaum/NvCustom/blob/main/colors/highlights.lua
https://github.com/zbirenbaum/NvCustom/blob/main/colors/init.lua

I'm happy to do it myself, but I have a lot on my plate right now. I will say I'll be doing this anyways next week as part of working on the customless rewrite, and I think siduck stated we are probably going to be taking care of that before he worries about anything 0.7 related: https://github.com/NvChad/NvChad/issues/922#issuecomment-1099751075

I may have misinterpreted what he said there though, so feel free to follow up with him.

**Comment by GreatestOfAllTimee** [comment]
I think if we want to merge this, we should merge on another branch (unless @siduck or @zbirenbaum want to merge on main branch). [`Neovim-v0.7.0`](https://github.com/neovim/neovim/releases/tag/v0.7.0) just released today. Probably it require some extra changes to make Nvchad run smooth on v0.7.

**Comment by siduck** [comment]
> I think if we want to merge this, we should merge on another branch (unless @siduck or @zbirenbaum want to merge on main branch). [`Neovim-v0.7.0`](https://github.com/neovim/neovim/releases/tag/v0.7.0) just released today. Probably it require some extra changes to make Nvchad run smooth on v0.7.

yes we'll wait till 22 for now, once this resolves! https://github.com/NvChad/NvChad/issues/922

**Comment by rauchg** [comment]
Looking forward to this!

**Comment by siduck** [comment]
> Looking forward to this!

oh wait, are you vercel's creator? :exploding_head:

**Comment by rauchg** [comment]
Yes and *huge* fan of NvChad 😁

**Comment by rfc2119** [comment]
Just wanted to add Timesweeper's detailed comment/round-up on the v0.7 release if anyone missed it: https://www.reddit.com/r/neovim/comments/u5si2w/breaking_changes_inbound_next_few_weeks_for/

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/tree/customless

**Comment by rfc2119** [comment]
Hey @siduck this link is 404'd: https://github.com/NvChad/NvChad/tree/customless
What was the conclusion of migrating to neovim 0.7 ?

**Comment by siduck** [comment]
@rfc2119 we already migrated to 0.7! btw that branch got deleted

**Pull request closed without merging**
