### PR TITLE
refactor(readme): make readme better

### PR DESCRIPTION
**Pull request by Gitleptune**
- Add links in Features section
- Refactor Bloat section
- Refactor Support section
- Add collapsible Themes section

### CODE REVIEW

**Comment by siduck76** [comment]
The support section doesn't need any refactoring

**Comment by Gitleptune** [comment]
I guess I can revert it but it's full of grammar mistakes and repetitions, I also thought that certain things from it weren't as relevant to the project.

**Comment by siduck76** [comment]
> I guess I can revert it but it's full of grammar mistakes and repetitions, I also thought that certain things from it weren't as relevant to the project.

yes revert it , correct that section grammatically rather than removing it

**Comment by siduck76** [comment]
Also whats this arrow for? 
image

clicking the title (theme showcase) must toggle the images in its section right?

**Comment by siduck76** [comment]
Also make this whole section toggleable : Very useful plugins used

**Comment by Gitleptune** [comment]
Alright, sorry it took so long. How is the Support section now?

Also fixed the collapsibles but they have to be like this because GitHub markdown is painful and puts an arrow on an empty line otherwise :/

image

**Pull request merged**
