### PR TITLE
Register mappings only if pluigin is enabled | Misc

### PR DESCRIPTION
**Pull request by Akianonymus**
Use setup of packer to load the mappings before

Load cmp on cmp module

### CODE REVIEW

**Comment by siduck** [comment]
@Akianonymus wait for this, i was thinking to remove whichkey ( will do a POLL )  and load mappings of all plugins in their setups, like we do for lspconfig 

```lua
  local lsp_mappings = utils.load_config().mappings.lspconfig
  utils.load_mappings({ lsp_mappings })
```

So i'd load the one in tabufline config too, so if its disabled then mappings will be too

**Comment by Akianonymus** [comment]
Ok, but you cannot move mappings to other place, it needs to be in packer setup block, because we need to load the mappings before the plugins are loaded, are we are lazy loading the plugins on the mappings ( most of it atleast ).

**Comment by siduck** [comment]
> Ok, but you cannot move mappings to other place, it needs to be in packer setup block, because we need to load the mappings before the plugins are loaded, are we are lazy loading the plugins on the mappings ( most of it atleast ).

yes it'll go in the setup part and we're currently not lazyloading the mappings, will do soon

**Comment by Akianonymus** [comment]
> yes it'll go in the setup part and we're currently not lazyloading the mappings, will do soon

Ok, ping when done.

**Comment by Akianonymus** [comment]
@siduck When merge.

**Review by siduck — APPROVED** [review]

**Pull request merged**
