### PR TITLE
refactor: add utils to the global scope

### LINKED ISSUE #1053: Why the utility functions are not in the global scope?
Why the utility functions are not in the global scope? 90% (if not all) of the files use at least one of the utility functions and having them in the global scope eliminates a lot of `require`s and makes the code base a lot cleaner.

### PR DESCRIPTION
**Pull request by ahhshm**
closes #1053

I will do the same thing to the extensions and the base46 plugins

### CODE REVIEW

**Comment by siduck** [comment]
@ahhshm why nvchad.map? cant we use map? we can just load core.utils in related files

**Comment by ahhshm** [comment]
Yes, it's probably cleaner but I think it should be clear where the `map` function comes from for example.

**Comment by ahhshm** [comment]
> _G syntax looks weird to me

we can define a global variable without `_G` but it has some benefits:
> One advantage of this structure is that it simplifies the internal implementation of Lua, because there is no need for a different data structure for global variables. The other (actually the main) advantage is that we can manipulate this table as any other table. To facilitate such manipulations, Lua stores the environment itself in a global variable _G. (Yes, _G._G is equal to _G.)

**Comment by siduck** [comment]
I just didnt know how the _G stuff worked so got confused

**Comment by ahhshm** [comment]
> I just didnt know how the _G stuff worked so got confused

I don't know either. I just know how to use it :)

**Comment by Akianonymus** [comment]
Please do revert this, having global functions have a lot of bad implications, should be avoided as much as possible.

**Comment by siduck** [comment]
> Please do revert this, having global functions have a lot of bad implications, should be avoided as much as possible.

wym :thinking:

**Comment by Akianonymus** [comment]
Well more memory usage, but to be honest, memory usage is not a realistic concern here i guess. It's much more important that the code be easy to follow and not have unpredictable results. Global functions are also globally modifiable too, so there's is that. But anyway, ignore me.

**Pull request merged**
