### PR TITLE
fix: perfomance issues with nvim-tree

### PR DESCRIPTION
**Pull request by zX3no**
There is quite a big delay when open nvim-tree for the first time. Disabling git intergration fixes it. 
Details: [nvim-tree#549](https://github.com/kyazdani42/nvim-tree.lua/issues/549)

### CODE REVIEW

**Comment by siduck76** [comment]
Would disabling git integration mean that the git diff stuff won't show on nvimtree?

**Comment by zX3no** [comment]
Yeah you won't be able to see changed files in the browser. Kind of annoying but it's better than a 3 second freeze for every git project. The creator of nvim-tree said they're working on a solution but it's going to take a while.

**Comment by siduck76** [comment]
> Yeah you won't be able to see changed files in the browser. Kind of annoying but it's better than a 3 second freeze for every git project. The creator of nvim-tree said they're working on a solution but it's going to take a while.

but thats a needed feature :l

**Comment by siduck76** [comment]
also this PR isnt properly formatted with stylua

**Comment by siduck76** [comment]
only changes you needed to make is 

image


I'll add an option in the chadrc for this after #465 gets merged!

**Comment by zX3no** [comment]
Sure. Also it would be nice to mention formatting in your [contribution guide](https://nvchad.netlify.app/contribute).

**Comment by G-Rowell** [comment]
@zX3no 

You're right! We totally do need a contribution guide, sorry for that.

We do have auto-styling with every PR here, so you hopefully shouldn't need to worry about it?

I never style my code properly, as our GitHub actions will clean it up automatically.
(See the commits in this PR)


Thank you for your PR,
we'll make to come back to this soon!

G

**Comment by siduck76** [comment]
@mxzel git stuff is enabled by default on nvimtree , just disable it in chadrc :)

**Pull request closed without merging**
