### PR TITLE
Change tab to 4

### PR DESCRIPTION
**Pull request by sangshuduo**

### CODE REVIEW

**Comment by siduck** [comment]
oops thats a scary PR :fearful: xD

**Comment by LeonHeidelbach** [comment]
@sangshuduo what even is this? Please explain what you change when creating such an extensive PR.

**Comment by sangshuduo** [comment]
@LeonHeidelbach  Sorry for my accident in submitting the PR to the upstream repo. I want to customize a few settings for myself. I cloned the NvChad to my account. But I don't know how to set my repo's default PR against myself rather than upstream. So I just found my mistake after the PR was created, then I just closed it.

**Comment by LeonHeidelbach** [comment]
> @LeonHeidelbach Sorry for my accident in submitting the PR to the upstream repo. I want to customize a few settings for myself. I cloned the NvChad to my account. But I don't know how to set my repo's default PR against myself rather than upstream. So I just found my mistake after the PR was created, then I just closed it.

@sangshuduo ah okay, no worries. You can select the target repo/branch for the PR either using the GitHub cli or the UI inside of a PR creation on the GitHub website.

**Comment by sangshuduo** [comment]
> > @LeonHeidelbach Sorry for my accident in submitting the PR to the upstream repo. I want to customize a few settings for myself. I cloned the NvChad to my account. But I don't know how to set my repo's default PR against myself rather than upstream. So I just found my mistake after the PR was created, then I just closed it.
> 
> @sangshuduo ah okay, no worries. You can select the target repo/branch for the PR either using the GitHub cli or the UI inside of a PR creation on the GitHub website.

Yes, but if GitHub provides a way to make downstream repo be target by default would make things easier. :)

**Comment by siduck** [comment]
@sangshuduo it would be better to just use the custom config only , it can control the entire defaults of nvchad

**Comment by LeonHeidelbach** [comment]
> > > @LeonHeidelbach Sorry for my accident in submitting the PR to the upstream repo. I want to customize a few settings for myself. I cloned the NvChad to my account. But I don't know how to set my repo's default PR against myself rather than upstream. So I just found my mistake after the PR was created, then I just closed it.
> > 
> > 
> > @sangshuduo ah okay, no worries. You can select the target repo/branch for the PR either using the GitHub cli or the UI inside of a PR creation on the GitHub website.
> 
> Yes, but if GitHub provides a way to make downstream repo be target by default would make things easier. :)

@sangshuduo Well it depends on who you are. Usually when you fork a repo and submit a PR you want it to be merged into the main repo, so I think it’s fine to be the default. You usually don’t submit PR’s to your fork when you just want to apply some changes.

But what @siduck said is true. You should add your changes into the custom folder rather than applying them to NVChad itself. Have a look at the documentation.

**Comment by sangshuduo** [comment]
@siduck  @LeonHeidelbach appreciated your suggestion. I will study it.

**Pull request closed without merging**
