### PR TITLE
fix(lsp): lsp on_attach was not called at normal mode

### LINKED ISSUE #1384: A bug in the undo operation
**Describe the bug**
First, 
I have set not to record history file modifications in my configuration file.
 `vim.opt.undofile = false`
Second,
When I open any file and then do undo directly, it shows that a change to the last line was undone.

**To Reproduce**
1. open a file
2. press ‘u’

**Screenshots**

https://user-images.githubusercontent.com/25720015/181228831-692303e1-352b-4c6e-933c-5db50d8b2226.mp4

**Desktop (please complete the following information):**
 - Operating System 
 manjaro linux
 - Terminal 
 konsole
 - Version of Neovim    
 NVIM v0.7.2

**Additional context**
 `PackerSync` has been executed.
When removing the personal configuration(custom folder), the problem persists.

### PR DESCRIPTION
**Pull request by tomasky**
fix #1384

### CODE REVIEW

**Comment by siduck** [comment]
@tomasky  

image

This is very heavy on startuptime

**Comment by siduck** [comment]
we just load lspconfig only when there's a file in the buffer

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/182029495-59fd21b0-5332-4591-b535-1c15ac74438b.mp4

also check https://github.com/williamboman/mason.nvim/issues/126#issuecomment-1193651563

**Comment by tomasky** [comment]
:do Filetype also solves this problem and does not introduce new problems
I just tested it

**Comment by tomasky** [comment]
Do you need me to resubmit it, or you can handle it yourself

**Comment by siduck** [comment]
> Do you need me to resubmit it ?, or you can handle it yourself

edit the PR and just use ``` vim.cmd "silent! do FileType"```, remove the BufEnter event too. Btw does this fix that undo issue?

**Comment by tomasky** [comment]
yes ,it fixed that undo issue, the pr has been updated

**Pull request merged**
