### PR TITLE
feat: Add config.plugins.status.snippets to enable/disable snippets

### PR DESCRIPTION
**Pull request by i3Cheese**
I thought many users dont use snippets, so they would like to disable it.

This option remove snippets plugins from order of lazy loading and remove it use from cmp mapping

### CODE REVIEW

**Comment by siduck** [comment]
@i3Cheese PR is fine but there's one issue! If the user disables snippets then that would load cmp at start i.e not at insertenter event!

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
@i3Cheese completion doesnt work at all :/ 

image

**Comment by siduck** [comment]
image

**Comment by siduck** [comment]
@i3Cheese if cmp makes needs snippets table for sure then ig i have to revert this commit

**Comment by i3Cheese** [comment]
> @i3Cheese if cmp makes needs snippets table for sure then ig i have to revert this commit or you would like to fix this issue

Okay, I will try to do this today.

**Pull request merged**
