### PR TITLE
Changed mappings to move between windows/terminals with Ctrl+h,j,k,l

### PR DESCRIPTION
**Pull request by JoakoV3**
I love how these configs are getting better every day!

There was no easy movements between terminals, vimtree nor split opened buffers. With this change, you can move between all of them easily without the mouse by pressing `Ctrl + h` ; `Ctrl + l` ; `Ctrl + j` ; `Ctrl + k` . I thought it should be having it by default.

### CODE REVIEW

**Review by Esequiel378 — APPROVED** [review]
Love this key mapping 👌

**Review by ashincoder — APPROVED** [review]
:+1:

**Comment by siduck76** [comment]
> ctrl + h is used for nvim tree focus

can we change it to leader nf?

**Comment by ashincoder** [comment]
better move nvim-tree toggle to `<leader>e`

**Comment by G-Rowell** [comment]
> better move nvim-tree toggle to `<leader>e`
> 

@siduck76

**Pull request merged**
