### PR TITLE
Suggestions on version control

### PR DESCRIPTION
**Pull request by lixvbnet**
Here's to show case my idea on version control NvChad as well as consumed plugins #1096

### CODE REVIEW

**Comment by siduck** [comment]
@lixvbnet this is more user specific and users can just redefine the plugin options in chadrc 

```lua
M.plugins = {
   user = {
      ["NvChad/nvterm"] = {
         commit = "xyz",
      },
   },
}```

**Comment by lixvbnet** [comment]
@siduck Yeah I know users can customize a specific plugin, but my point is when tagging NvChad as a release, it should "snapshot" its dependent plugins as well.

**Comment by siduck** [comment]
@lixvbnet the releases are just to track nvchad config history, arent supposed to be used. You need to use the master config only, release will break when new neovim versions release regardless of plugin's working commit

**Comment by lixvbnet** [comment]
@siduck all right.

**Pull request closed without merging**
