### PR TITLE
feat: Added highlight on yank.

### PR DESCRIPTION
**Pull request by ashincoder**

### CODE REVIEW

**Comment by ashincoder** [comment]
https://user-images.githubusercontent.com/83629316/130107859-a13c7c9b-676e-475f-86b7-a9c53d5281bc.mp4

**Comment by siduck76** [comment]
@ashincoder The highlight on yank looks kinda annoying :l , Ig maybe this will be added to chad user configs.

**Comment by ashincoder** [comment]
> @ashincoder The highlight on yank looks kinda annoying :l , Ig maybe this will be added to chad user configs.

Bruh, I will change the colors and also make it user_configurable via chadrc.lua. Until then I'll make it a draft

**Comment by siduck76** [comment]
> > @ashincoder The highlight on yank looks kinda annoying :l , Ig maybe this will be added to chad user configs.
> 
> Bruh, I will change the colors and also make it user_configurable via chadrc.lua. Until then I'll make it a draft

I mean , this feature feels very unneeded bruh!

**Comment by Pocco81** [comment]
@ashincoder I agree with @siduck76. The first time I used this thing was with LunarVim and since the beginning it felt kind of annoying, so I removed this.

**Comment by Dark-Matter7232** [comment]
Make it an optional feature, looks pretty nice.

**Comment by ashincoder** [comment]
> > > @ashincoder The highlight on yank looks kinda annoying :l , Ig maybe this will be added to chad user configs.
> > 
> > 
> > Bruh, I will change the colors and also make it user_configurable via chadrc.lua. Until then I'll make it a draft
> 
> I mean , this feature feels very unneeded bruh!

If u ask me there are some features that are uneeded. But if he user wants it can be added..

**Pull request closed without merging**
