### PR TITLE
(maint): update format.yml git commands

### PR DESCRIPTION
**Pull request by vladdoster**
@siduck76 I am opening this PR again because @ashincoder closed the original (#522) and then pushed changes that don't work and still do what I am proposing changes for. 

- remove negated conditional check
- remove `git add .` by using `--all` opt in `git commit`
- use long opt flags

Signed-off-by: Vladislav Doster <mvdoster@gmail.com>

### CODE REVIEW

**Comment by vladdoster** [comment]
You can not do the following:

```bash
git commit --all -m "chore: format with stylua" init.lua lua/**
```

You get the following error:

```bash
$ git commit --all --message "(maint): Update init.lua" init.lua lua/**
fatal: paths 'init.lua ...' with -a does not make sense
```

**Comment by vladdoster** [comment]
I'd highly suggest restricting users from making changes so freely. It seems @ashincoder did not attempt to test his changes.

**Comment by ashincoder** [comment]
@vladdoster The reasons I closed the PR:

1. I was editing the formatter.yml and didn't wanna cause any conflicts
2. I did notice this yesterday night but I had merged the test branch.
3. Also we don't want small commits like this. We try to make our git log as clean as possible.
4. If this was a really important PR then we won't twice and just merge it but since the formatter works now. Also I don't see the error u reported in the CI output log

```
  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git config --local user.name "github-actions[bot]"
  if ! [[ -z $(git status -s) ]]; then
    git commit --all -m "chore: format with stylua" init.lua lua/**
  fi
  shell: /usr/bin/bash -e {0}
```

**Comment by ashincoder** [comment]
Mr.@vladdoster to which branch are u pushing the changes.
2021-10-04-122314_801x473_scrot

This seems fine to me.

**Comment by vladdoster** [comment]
@ashincoder The commit you're referencing is a merge commit. There are two commits in this PR.

**Comment by ashincoder** [comment]
> @ashincoder The commit you're referencing is a merge commit. There are two commits in this PR.

Yes and that merge commit is useless.

**Comment by vladdoster** [comment]
Also the comment about "small commits" makes no sense.

See commits #520, #514, and #415 for a few examples.

When this is merged, use a squash commit and it will be squashed.

**Comment by ashincoder** [comment]
> Also the comment about "small commits" makes no sense.
> 
> See commits #520, #514, and #415 for a few examples.
> 
> When this is merged, use a squash commit and it will be squashed.

by small commits I mean, which are not important.

**Comment by ashincoder** [comment]
Now I don't mind merging this since this will be squashed and made as 1 commit.

**Pull request merged**
