### PR TITLE
chore: add contributing.md

### PR DESCRIPTION
**Pull request by marvelman3284**
#310 
basically just copied the contributing section from the website and added a permanent link to the discord at the end

### CODE REVIEW

**Review by G-Rowell — APPROVED** [review]
Thanks again Marvel!!!

I like this, it's good :)

As a note: We may have to update both contributing pages in the future when we properly implement a dev branch.

**Comment by marvelman3284** [comment]
Yep, sounds good.

**Comment by ashincoder** [comment]
> Thanks again Marvel!!!
> 
> I like this, it's good :)
> 
> I checked in the GitHub markdown viewer and it seems to render decently.
> 
> As a note: We may have to update both contributing pages in the future when we properly implement a dev branch.

sorry to sound rude or interrupt. This is my opinion: 
I don't think contributing.md should be quite as large and intimidating. If we want to attract the users to take part in the development We have to make it short and sweet.

**Comment by G-Rowell** [comment]
good point

**Comment by siduck76** [comment]
agreed

**Pull request merged**
