### PR TITLE
fix: let override function works,fix #1287 #1278

### LINKED ISSUE #1287: Cannot import any plugin modules inside of custom/*
**Describe the bug**
This is pretty much the same issue as #1182, but i can't seem to get it to work, even through several reinstalls of nvchad and nvim.  If i require any module outside of the custom directory, specifically 'telescope.actions' in this case, nvim refuses to run the custom/chadrc.lua. When i put in a print to see what the issue was i got the following:

```
module 'telescope.actions' not found:\n\tno field package.preload['telescope.actions']\n\tno file './telescope/actions.lua'\n\tno file '/
usr/local/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-beta3/telescope/actions.lua'\n\tno file '/usr/local/share/lua/5.1/telescope/actions.lua'\n\tno file '/usr/local/share/lua/5.1/teles
cope/actions/init.lua'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/telescope/actions.lua'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/tel
escope/actions/init.lua'\n\tno file './telescope/actions.so'\n\tno file '/usr/local/lib/lua/5.1/telescope/actions.so'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/telesco
pe/actions.so'\n\tno file '/usr/local/lib/lua/5.1/loadall.so'\n\tno file './telescope.so'\n\tno file '/usr/local/lib/lua/5.1/telescope.so'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-2022041
1/lib/lua/5.1/telescope.so'\n\tno file '/usr/local/lib/lua/5.1/loadall.so'
```

**To Reproduce**
1.  clean nvim and nvchad install
2. chadrc:
```
local M = {}

M.ui = {
   theme = "tokyodark",
}

local actions = require('telescope.actions')

M.plugins = {
  override = {
    ["nvim-telescope/telescope.nvim"] = {
      defaults = {
        mappings = {
          i = {
            ["jkk"] = actions.close,
          },
        },
      },
    }
  }
}

return M
```
3. config errors.

**Expected behavior**
I want to override telescope binds using their actions, but this issue prevents me from doing that.

**Desktop:**
 - Operating System: MacOS
 - Terminal: kitty
 - Version of Neovim: 0.7

### PR DESCRIPTION
**Pull request by tomasky**

### CODE REVIEW

**Review by siduck — APPROVED** [review]

**Review by siduck — APPROVED** [review]

**Comment by tomasky** [comment]
why not check `user_table` is table ?

**Comment by siduck** [comment]
@tomasky its already checked 

image

**Comment by tomasky** [comment]
but if this a function , user_table() is a table ?

**Comment by tomasky** [comment]
Maybe it's a good idea to just print an error tips if user_table or user_table() is not a table

**Comment by tomasky** [comment]
no ,i mean this,and  It is necessary to verify that user_table is a function


```lua
  user_table = type(user_table) == "table" and user_table or user_table()
 if type(user_table) == "table" then

end
```

**Comment by siduck** [comment]
```lua
  user_table = type(user_table) == "function" and user_table() or user_table
```
Then

**Comment by tomasky** [comment]
Anyway, this is a necessary, i think, then It's the same as before pr

```lua
  user_table = type(user_table) == "function" and user_table() or user_table

 if type(user_table) == "table" then

end
```

**Comment by siduck** [comment]
We should assume that the user uses a table by default so we dont need to check it

**Comment by tomasky** [comment]
alright, i think you can give some error tips when some fresh users dont known this and dont read some docs, Otherwise,  they keep asking relevant questions

**Comment by siduck** [comment]
@tomasky if they dont read the docs then they are not allowed to use nvchad. I dont get how can someone use nvchad without reading the docs!!

**Comment by siduck** [comment]
btw if you can help with this issue https://github.com/NvChad/NvChad/issues/1276

Having a hard time implementing it

**Comment by tomasky** [comment]
Maybe you can add more examples in examples/chadrc.lua,  Just a suggestion

**Pull request merged**
