### PR TITLE
updated lua/plugins/configs/nvimtree.lua icons

### PR DESCRIPTION
**Pull request by mmsaeed509**
# update  nvim tree icons

<h1 align="center"> :herb: default icons after installation [new] </h1>
 
Screenshot_2022-05-31-05-47-02_3840x1080

Screenshot_2022-05-31-05-57-28_3840x1080

<h1 align="center"> :herb: default icons after installation [old] </h1>

Screenshot_2022-05-31-05-51-03_3840x1080

### CODE REVIEW

**Comment by siduck** [comment]
You need to set proper nerdfonts

**Comment by siduck** [comment]
You don't get the icons because you use items, I can tell it

**Comment by javidrashid** [comment]
@siduck Can I get icons if I don't use NerdFont? I have my icons working fine as usual but I prefer Source Code Pro font and when I let terminal use my Source code pro font, I don't have the file icons.

**Comment by siduck** [comment]
@javidrashid i dont think so :/ , nvimwebdevicons uses nerdfonts . Just patch nerdfonts to it then, there's a script on nerdfonts repo

or if you are on arch then check this 

https://aur.archlinux.org/packages/nerd-fonts-source-code-pro

**Pull request closed without merging**
