### PR TITLE
remove event="VimEnter"

### PR DESCRIPTION
**Pull request by bryant-the-coder**

### CODE REVIEW

**Comment by siduck** [comment]
why?

**Comment by bryant-the-coder** [comment]
it has been discussed before in the discord group. the startup will be the same even without this event.

**Comment by siduck** [comment]
> it has been discussed before in the discord group. the startup will be the same even without this event.
ohh yes, btw i found out that using module= "packer" decreases startuptime 

image

**Comment by siduck** [comment]
i get weird issue when packer's not lazy loaded 
image

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/160393893-e9a092ad-39c3-4b9f-91ac-c506c1ffe9e3.mp4

So i shall close this pr as it brings more bad than good!

**Comment by bryant-the-coder** [comment]
uhm its bufferline issue ...

please see bufferline readme is in the error

**Comment by siduck** [comment]
its not, we have upto date bufferline config

https://user-images.githubusercontent.com/59060246/160405023-a9e7e510-017e-41f3-b163-2af78f1c5d77.mp4

**Comment by siduck** [comment]
we dont get the bufferline issue with vimenter

**Pull request closed without merging**
