### PR TITLE
fix: default mappings can now be properly disabled, independent of load order

### PR DESCRIPTION
**Pull request by LeonHeidelbach**
@siduck The title says it all. This implements what I outlined here https://github.com/NvChad/NvChad/issues/1071#issuecomment-1125925059.

### CODE REVIEW

**Comment by siduck** [comment]
dang soo many looop, I wanted to keep the utils.lua smol and simple :c

**Comment by LeonHeidelbach** [comment]
> dang soo many loops! I wanted to keep the utils.lua smol and simple :c

@siduck Well unfortunately there is no other simpler way to check if there are doubling key bindings.

**Comment by siduck** [comment]
> > dang soo many loops! I wanted to keep the utils.lua smol and simple :c
> 
> @siduck Well unfortunately there is no other simpler way to check if there are doubling key bindings.

we dont have to, the users must disable the keys in their original tables

**Comment by LeonHeidelbach** [comment]
> > > dang soo many loops! I wanted to keep the utils.lua smol and simple :c
> > 
> > 
> > @siduck Well unfortunately there is no other simpler way to check if there are doubling key bindings.
> 
> we dont have to, the users must disable the keys in their original tables

@siduck that's the thing, it does unfortunately not just work like that. Currently it is dependent on the load order in which the key bindings are mapped. If the specific key binding you want to disable for one plugin, but want to use for another it with another plugin, it will be assigned the value that is last assigned to it in alphabetical order of the `M.<PLUGIN_NAME>` in your table. That means that the load order can just change when you add a new plugin to your mapping list. My prune function will resolve this issue. There is unfortunately no other way. Try it out yourself:

Go to your custom mappings list and add `M.a` and try to override a key for `M.nvimtree` or any other plugin that starts with a letter after "a". This will not work. Now change `M.a` to `M.z` and it should work. This is not expected behavior so it is necessary to completely remove overridden keys from the default table at the time when `wk.register` is called.

**Comment by siduck** [comment]
@LeonHeidelbach  works here

image

**Comment by LeonHeidelbach** [comment]
@siduck try moving it before `M.nvimtree` maybe it's not in alphabetical order but just assignment order. I had this issue multiple times and tried a couple different arrangements in my mappings config.

**Comment by LeonHeidelbach** [comment]
@siduck it could as well be a random order thing but this issue came up with multiple mappings. And the prune function does not add that much bulk to the utils :wink:

**Comment by siduck** [comment]
> @siduck try moving it before `M.nvimtree` maybe it's not in alphabetical order but just assignment order. I had this issue multiple times and tried a couple different arrangements in my mappings config.

i tried but cant reproduce your issue!

**Comment by LeonHeidelbach** [comment]
@siduck hop on discord and I will show you

**Review by siduck — APPROVED** [review]

**Pull request merged**
