### PR TITLE
Simplify plugin management even more (#1518)

### PR DESCRIPTION
**Pull request by siduck**
## Things that are new with the syntax : 

1. You can now override plugin configs without entering chadrc, just put it in `override_options` of your plugin table.

2. To remove a plugin, just set it to false 

## Examples : 

```lua
-- chadrc.lua
M.plugins = require "custom.plugins"
```

```lua
-- custom/plugins.lua
return {
  -- Install a plugin
  ["Pocco81/TrueZen.nvim"] = {},

  -- Override packer definition options of default plugin
  ["neovim/nvim-lspconfig"] = {
    event = "VimEnter",
  },

  -- Override options from plugin config
  ["kyazdani42/nvim-tree.lua"] = {
    override_options = {
      view = {
        side = "right",
        width = 25,
      },
    },
  },

  -- remove default plugin , set it to false
  ["lewis6991/gitsigns.nvim"] = false,
}
```

The above is same as this : 

```lua
-- chadrc.lua
M.plugins = {
 
   ["Pocco81/TrueZen.nvim"] = {},
   ....
}
```

### CODE REVIEW

**Comment by tomasky** [comment]
@siduck  Is  the  custom/plugins.lua file  allowed to  require lua module?

**Comment by siduck** [comment]
> @siduck Is the custom/plugins.lua file allowed to require lua module?

yes  

```lua
  ["hrsh7th/nvim-cmp"] = {
    override_options = function()
      local cmp = require "cmp"

      return {
        mapping = {
          ["<C-d>"] = cmp.mapping.scroll_docs(-8),
        },
      }
    end,
  },

```

**Comment by tomasky** [comment]
no ,i mean ,
```lua
local configs = require "custom.configs"
["hrsh7th/nvim-cmp"] = {
    override_options = configs.cmp
  },

```

**Comment by siduck** [comment]
> no ,i mean ,
> 
> ```lua
> local configs = require "custom.configs"
> ["hrsh7th/nvim-cmp"] = {
>     override_options = configs.cmp
>   },
> ```

yes this will work

**Comment by Akianonymus** [comment]
Also, what happened to all configs returning the table ? I don't see that change

**Comment by Akianonymus** [comment]
@siduck Yes, did you forget, it was being discussed in that issue.

**Comment by siduck** [comment]
With the new syntax of overriding plugin configs, we no longer need to import plugin configs so we don't have to export them ( return their tables )

**Comment by Akianonymus** [comment]
> With the new syntax of overriding plugin configs, we no longer need to import plugin configs so we don't have to export them ( return their tables )

Returning tables so user can fetch and do whatever they want with it, it wasn't because it was needed with the new syntax.

**Comment by siduck** [comment]
What will the user do apart from overriding the plugin config?

**Comment by siduck** [comment]
> Sometimes, i want a part of the config, like capabilities part of lspconfig, etc and use it somewhere. Yes, one could just always copy paste but that's the solution to everything anyway, lol.
> 
> Also, it's more about improving the config structure. Each plugin should return a table, containing two things, a setup function, and a config table. I am just trying to remove the unevenness of the config.

capabilities in lspconfig is already returned, you already use it in your custom config . Anything other edge cases?

**Comment by Akianonymus** [comment]
> also its not un-evenness, even if you look out into non nvchad configs ( general nvim configs ) the whole plugin config + its setup call is in the same file and not separated into functions

We will talk about it later, anyway, first let't merge this first, i will test it soon.

**Comment by siduck** [comment]
i tested it here already but test it from dev branch directly first then I'll merge this 

```lua
M.options = {
	nvChad = {
		update_branch = "dev",
	},
}
```

**Comment by Akianonymus** [comment]
Your dev branch is outdated btw, doesn't have the latest commits of master ( therefore breaks colorizer ).

ALso i got this error

`
packer.nvim: Error running config for ui: [string "..."]:0: attempt to call field 'nvchad_ui' (a nil value)
`

**Comment by Akianonymus** [comment]
Nevermind, just colorizer is broken, rest fine, just pick the latest commits from master. Colorizer will work fine too i guess.

Rest of the stuff will check tonight ( new override method )

**Comment by Akianonymus** [comment]
No changes for now, just pulled the latest commit and force pushed.

**Comment by siduck** [comment]
dang soo much extra code! waiting for next month to clean it all :angry: :rocket:

**Comment by Akianonymus** [comment]
@siduck 😂 Btw, do pin a issue, so users can change, with the link to the guide.

**Pull request merged**
