### PR TITLE
fix: empty snippets

### PR DESCRIPTION
**Pull request by i3Cheese**

### CODE REVIEW

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
oops i didnt test this. @i3Cheese 
image
image

it stopped completion for functions and inbuilt lsp snippets :(

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/151725481-03358219-e137-44d2-972f-384a3d818a52.mp4

**Comment by i3Cheese** [comment]
@siduck have you done :PackerSync? If you dont do this, cmp will see snippets, but cant expand it cause we turned it off

**Comment by siduck** [comment]
> @siduck have you done :PackerSync? If you dont do this, cmp will see snippets, but cant expand it cause we turned it off

yes i tried that, but it didnt work. Does it work for you?

**Pull request merged**
