### PR TITLE
Restructure config | Move some to a packer plugin | Lot of cleanup

### PR DESCRIPTION
**Pull request by Akianonymus**
* move teleacope files, updater and related utils to
  https://github.com/NvChad/extensions

* restructure config file and directory structure

* expose mappings for better escape

* allow multiple mappings for some

* improve merge table function for the same

* move autocommands to a seperate file

* rearrange everything alphabetically where sanely possible

* rearrange packer plugin list on the basis of trigerred state

config structure now

 ```
├──  init.lua
├──  LICENSE
├──  lua
│  ├──  chadrc.lua
│  ├──  colors
│  │  ├──  highlights.lua
│  │  ├──  init.lua
│  │  └──  themes
│  │     ├──  chadracula.lua
│  │     ├──  everforest.lua
│  │     ├──  gruvchad.lua
│  │     ├──  javacafe.lua
│  │     ├──  mountain.lua
│  │     ├──  norchad.lua
│  │     ├──  one-light.lua
│  │     ├──  onedark.lua
│  │     ├──  tokyonight.lua
│  │     └──  tomorrow-night.lua
│  ├──  core
│  │  ├──  autocmds.lua
│  │  ├──  init.lua
│  │  ├──  mappings.lua
│  │  ├──  options.lua
│  │  └──  utils.lua
│  ├──  default_config.lua
│  └──  plugins
│     ├──  configs
│     │  ├──  autopairs.lua
│     │  ├──  autosave.lua
│     │  ├──  bufferline.lua
│     │  ├──  chadsheet.lua
│     │  ├──  compe.lua
│     │  ├──  dashboard.lua
│     │  ├──  gitsigns.lua
│     │  ├──  icons.lua
│     │  ├──  lspconfig.lua
│     │  ├──  luasnip.lua
│     │  ├──  nvimtree.lua
│     │  ├──  others.lua
│     │  ├──  statusline.lua
│     │  ├──  telescope.lua
│     │  ├──  treesitter.lua
│     │  └──  zenmode.lua
│     ├──  init.lua
│     └──  packerInit.lua
└──  README.md
```

### CODE REVIEW

**Comment by Akianonymus** [comment]
This needs a lot of testing, to handle any edgecases left

Telescope plugin: https://github.com/NvChad/core

**Comment by ashincoder** [comment]
lua```
cmd "silent! command PackerClean lua require 'plugins' require('packer').clean()" 
```
Add it in mappings.lua

**Comment by G-Rowell** [comment]
Just wondering why there is a `lua/core` folder in here, I thought we were going to move a whole lot of files to the `core` plugin?
(that being said, I've just glanced through this PR)

**Comment by Akianonymus** [comment]
> Just wondering why there is a `lua/core` folder in here, I thought we were going to move a whole lot of files to the `core` plugin?
> (that being said, I've just glanced through this PR)

The core repo name should probably be extensions or something.

Obviously the base stuff will be not moved

**Review by siduck76 — APPROVED** [review]

**Pull request merged**
