### PR TITLE
fix: don't hide dot files by default

### PR DESCRIPTION
**Pull request by dunglas**
Hi,

Thanks for this great config!

Hiding dot files by default is counterintuitive and hurts the developer experience as most projects relies on dot files for CI and CD (`.github/`, `.gitlab-ci.yml`...).

This PR changes the default config to show dot files.

### CODE REVIEW

**Comment by siduck76** [comment]
@dunglas this is gonna show dotfiles by default which feels messy . 

with dotfiles : 
image

without it : 

image

**Comment by Akianonymus** [comment]
I will add a option in config to customize

**Comment by dunglas** [comment]
I know I can switch, but hiding dot files by default doesn't fit the IDE use case, does it?

AFAIK most IDEs show dot files by default.

**Comment by Akianonymus** [comment]
@dunglas Yep, it is annoying, atleast for me.

**Comment by siduck76** [comment]
> I know I can switch, but hiding dot files by default doesn't fit the IDE use case, does it?
> 
> AFAIK most IDEs show dot files by default.

oh :(

**Comment by siduck76** [comment]
I'll think about this

**Pull request merged**
