### PR TITLE
[ Chore ] Added FUNDING.yml

### PR DESCRIPTION
**Pull request by SkwalExe**
image

The repo admin will have to enable the `sponsor button` in the settings 
image

I hope this helps 😊

### CODE REVIEW

**Comment by siduck** [comment]
sorry It would not be appropriate for me to take donations. Read the support section in the readme. Thanks for the effort tho!

**Comment by shaunsingh** [comment]
If you look at the `FUNDING.yml` file itself, it has links to your charities. Please kindly reconsider this pull request

**Comment by SkwalExe** [comment]
The links are the following : 
image

**Comment by siduck** [comment]
> If you look at the `FUNDING.yml` file itself, it has links to your charities. Please kindly reconsider this pull request

those are not my charities. I randomly found them on  charity related websites.

**Comment by siduck** [comment]
oh my bad i didnt read your text properly xD

**Comment by siduck** [comment]
> The links are the following : image

but still i wouldnt have the sponsor button. Many would have a bad impression regarding it unless they know that its a charity link

**Pull request closed without merging**
