### PR TITLE
added gc and gb as keys to trigger lazy load on comment plugin

### PR DESCRIPTION
**Pull request by primeapple**
The `Comment.nvim` plugin now correctly lazy loads. :)
Before it did not lazy load for things like `gcaw`, `gbaw` in normal mode or `gc` in visual mode.

### CODE REVIEW

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
@primeapple send the PR again, idk why im not able to merge it. Where's the conflicts?

**Comment by primeapple** [comment]
Will send it again later this day :)

**Comment by peterpme** [comment]
:wave: Is the problem here the `gcc` commands vs. `gc`, `gb`? For example, I use `gcc` myself - is that the trade-off?

**Comment by siduck** [comment]
cant we have gcc and gc both at the same time?

**Comment by primeapple** [comment]
The thing is, that `gc` implies `gcc` ;-)  
So as soon as someone types `gc` the plugin is being loaded.

We have to get a list of all the used prefixes and put them into this list. For `Comment.nvim` this is `gc` and `gb`.

**Comment by primeapple** [comment]
See #997

**Pull request closed without merging**
